import {
  faBars,
  faBell,
  faCalculator,
  faChartLine,
  faChevronDown,
  faChevronRight,
  faChevronUp,
  faCircleInfo,
  faClose,
  faDownload,
  faMoon,
  faSun,
  faUser,
} from "@fortawesome/free-solid-svg-icons";

export const AVAILABLE_ICONS = {
  bars: faBars,
  chevronDown: faChevronDown,
  chevronRight: faChevronRight,
  chevronUp: faChevronUp,
  bell: faBell,
  download: faDownload,
  user: faUser,
  lineChart: faChartLine,
  calculator: faCalculator,
  info: faCircleInfo,
  close: faClose,
  lightTheme: faSun,
  darkTheme: faMoon,
};
